#!/usr/bin/env bash
#
# 鼠鬚管 + 雾凇拼音 一键安装 / 更新
# Squirrel + rime-ice one-shot install / update
#
#   curl -fsSL https://raw.githubusercontent.com/ziangchen7/rime-config/main/install.sh | bash
#
# 幂等：重复跑安全。每次都会把 brew 包、plum、词库、本仓库配置拉到最新。
# Idempotent. Every run pulls brew casks, plum, dictionaries and this repo to latest.

set -euo pipefail

REPO_URL="https://github.com/ziangchen7/rime-config.git"
RIME_DIR="$HOME/Library/Rime"
PLUM_DIR="$HOME/plum"
SQUIRREL="/Library/Input Methods/Squirrel.app/Contents/MacOS/Squirrel"

if [[ -t 1 ]]; then
  B=$'\033[1m'; G=$'\033[32m'; Y=$'\033[33m'; R=$'\033[31m'; N=$'\033[0m'
else
  B=''; G=''; Y=''; R=''; N=''
fi
step() { printf '\n%s==>%s %s%s%s\n' "$G" "$N" "$B" "$1" "$N"; }
info() { printf '    %s\n' "$1"; }
warn() { printf '    %s%s%s\n' "$Y" "$1" "$N"; }
die()  { printf '\n%s错误 Error:%s %s\n' "$R" "$N" "$1" >&2; exit 1; }

# 脚本自身在仓库里，checkout 会覆盖它。先挪到临时目录重新执行，避免边跑边被改。
# This script lives in the repo; re-exec from a temp copy so checkout can't
# rewrite it mid-run.
if [[ "${RIME_SELFCOPY:-}" != "1" && "${BASH_SOURCE[0]:-}" == "$RIME_DIR"/* ]]; then
  tmp="$(mktemp -t rime-install)"
  cat "${BASH_SOURCE[0]}" > "$tmp"
  RIME_SELFCOPY=1 exec bash "$tmp" "$@"
fi

step "环境检查 / Preflight"
[[ "$(uname -s)" == "Darwin" ]] || die "只支持 macOS / macOS only"
command -v git >/dev/null || die "需要 git。装 Xcode 命令行工具：xcode-select --install"
if ! command -v brew >/dev/null; then
  die "需要 Homebrew。见 https://brew.sh / Homebrew required"
fi
info "macOS $(sw_vers -productVersion) $(uname -m)"
info "$(brew --version | head -1)"

step "输入法与字体 / Input method and fonts"
# Plangothic 补 CJK 扩展 A~G 区，拆字候选里的生僻字才不会显示成方框
# Plangothic covers CJK Ext A-G so rare characters don't render as tofu
for cask in squirrel-app font-plangothic; do
  if brew list --cask "$cask" &>/dev/null; then
    info "$cask 已装，检查更新 / installed, checking for updates"
    brew upgrade --cask "$cask" 2>/dev/null || true
  else
    info "安装 $cask / installing"
    brew install --cask "$cask"
  fi
done

step "Rime 包管理器 plum / Package manager"
if [[ -d "$PLUM_DIR/.git" ]]; then
  info "已存在，拉取最新 / exists, pulling"
  git -C "$PLUM_DIR" pull --quiet --ff-only || warn "plum 拉取失败，用现有版本继续 / pull failed, continuing"
else
  info "克隆 / cloning"
  git clone --quiet https://github.com/rime/plum.git "$PLUM_DIR"
fi

step "词库 / Dictionaries"
# rime-install 对已有包会自动 git pull，所以这一步同时负责安装和更新
# rime-install git-pulls existing packages, so this both installs and updates
info "雾凇拼音 rime-ice"
( cd "$PLUM_DIR" && bash rime-install iDvel/rime-ice )
info "拆字带声调注音词典 / tone-marked reading dictionaries"
( cd "$PLUM_DIR" && bash rime-install mirtlecn/rime-radical-pinyin:extra )

step "配置 / Config"
mkdir -p "$RIME_DIR"
cd "$RIME_DIR"

if [[ -d .git ]] && git remote get-url origin 2>/dev/null | grep -q "rime-config"; then
  # 已是本仓库。有未提交改动就先 stash，不静默丢弃。
  # Already this repo. Stash local changes rather than discarding them.
  if [[ -n "$(git status --porcelain)" ]]; then
    stamp="install.sh 自动暂存 $(date '+%Y-%m-%d %H:%M:%S')"
    git stash push --quiet --include-untracked -m "$stamp" 2>/dev/null || true
    warn "检测到本地未提交改动，已 stash 保存 / local changes stashed"
    warn "恢复：git -C \"$RIME_DIR\" stash pop"
  fi
  info "拉取最新配置 / pulling latest"
  git fetch --quiet origin main
  git checkout --quiet -B main origin/main
else
  # 首次部署。已有的同名配置先备份，不直接覆盖。
  # First deploy. Back up any existing config files instead of overwriting.
  backup="$RIME_DIR/_backup_$(date '+%Y%m%d_%H%M%S')"
  found=0
  for f in *.custom.yaml; do
    [[ -e "$f" ]] || continue
    [[ $found -eq 0 ]] && mkdir -p "$backup" && found=1
    mv "$f" "$backup/"
  done
  [[ $found -eq 1 ]] && warn "原有 *.custom.yaml 已备份到 ${backup##*/} / backed up"

  git init --quiet
  git remote add origin "$REPO_URL" 2>/dev/null || git remote set-url origin "$REPO_URL"
  info "拉取配置 / fetching config"
  git fetch --quiet origin main
  git checkout --quiet -f -B main origin/main
fi
info "已同步到 $(git log -1 --format='%h %s' | cut -c1-60)"

step "生成词频表 / Generating frequency table"
# char_freq.lua 是从词库派生的，不入库：词库更新后就该重算，
# 留在仓库里还会在多台机器间产生无意义的冲突。
# Derived from the dictionaries, deliberately untracked: it must be
# regenerated whenever they update, and tracking it causes cross-machine churn.
freq_src="$(mktemp -t rime-freq)"
if compgen -G "$RIME_DIR/cn_dicts/*.dict.yaml" >/dev/null; then
  LC_ALL=en_US.UTF-8 awk -F'\t' 'NF>=3 && $1 ~ /^.$/ {print $1"\t"$3}' \
      "$RIME_DIR"/cn_dicts/*.dict.yaml \
    | LC_ALL=C sort -t$'\t' -k2 -rn \
    | awk -F'\t' '!seen[$1]++' > "$freq_src"
  n=$(grep -c '' "$freq_src" || true)
  if (( n < 5000 )); then
    warn "只提取到 $n 个单字，异常偏少，跳过生成 / suspiciously few, skipping"
    warn "拆字重排会降级为只按码点分档 / filter falls back to tier-only sorting"
  else
    mkdir -p "$RIME_DIR/lua"
    {
      echo "-- 单字词频排名，由 install.sh 从 cn_dicts/*.dict.yaml 生成，请勿手改。"
      echo "-- Generated by install.sh from cn_dicts. Do not edit; not tracked in git."
      echo "-- 数字是排名，1 = 最常用。不在表里的字视为生僻字/异体字。"
      echo "return {"
      awk -F'\t' '{printf "[\"%s\"]=%d,", $1, NR; if (NR%12==0) printf "\n"}' "$freq_src"
      echo ""
      echo "}"
    } > "$RIME_DIR/lua/char_freq.lua"
    info "$n 个单字 / entries, $(du -h "$RIME_DIR/lua/char_freq.lua" | cut -f1)"
  fi
else
  warn "找不到 cn_dicts，跳过 / cn_dicts not found, skipping"
fi
rm -f "$freq_src"

step "部署 / Deploy"
if [[ -x "$SQUIRREL" ]]; then
  "$SQUIRREL" --reload &>/dev/null || warn "自动部署失败，请手动点菜单栏「重新部署」"
  info "已触发重新部署 / deploy triggered"
else
  warn "找不到鼠鬚管，请手动部署 / Squirrel not found, deploy manually"
fi

printf '\n%s完成 / Done%s\n\n' "$G$B" "$N"
info "若首次安装，还需在 系统设置 → 键盘 → 输入方式 中添加「鼠鬚管」"
info "First install: add Squirrel in System Settings → Keyboard → Input Sources"
