--[[
拆字候选重排：常用字提到前面，生僻字降到后面。

起因：radical_pinyin 词库里同一拆法常匹配几十个字，权重大多是 1，
同权重就按词库行号排。以 cao'hui（草+惠）为例，21 个匹配里 13 个是
CJK 扩展 B/C/D 区的字，另有 5 个是主词库里都没有的异体字，
把「荟」垫到了第 18 位。

分四档，只重排不删除 —— 生僻字仍打得出来，只是排在后面。
拆字的用途之一就是打生僻字，直接过滤掉本末倒置。

  第 1 档  基本区 + 在主词库里，按词频排（越常用越前）
  第 2 档  基本区但主词库没有（异体字、罕用字）
  第 3 档  CJK 扩展 A 区
  第 4 档  CJK 扩展 B 区及以后

char_freq.lua 重新生成（词库更新后想同步频率时用）：
  cd ~/Library/Rime
  awk -F'\t' 'NF>=3 && $1 ~ /^.$/ {print $1"\t"$3}' cn_dicts/*.dict.yaml \
    | sort -t$'\t' -k2 -rn | awk -F'\t' '!seen[$1]++' > /tmp/freq.txt
  然后按本文件生成时的格式写成 lua 表
--]]

-- char_freq.lua 由 install.sh 生成，不入库（见该脚本「生成词频表」一节）。
-- 缺失时降级为只按码点分档，仍能把扩展区生僻字降后，只是不按词频细排。
-- Generated by install.sh, not tracked. If absent, degrade to tier-only sorting.
local ok, freq = pcall(require, 'char_freq')
if not ok or type(freq) ~= 'table' then freq = {} end

-- 返回 档位, 词频排名
local function rank_of(text)
    if not text or text == '' then return 2, 0 end
    local ok, cp = pcall(utf8.codepoint, text)
    if not ok or not cp then return 2, 0 end
    if cp >= 0x20000 then return 4, 0 end                  -- 扩展 B 及以后
    if cp >= 0x3400 and cp <= 0x4DBF then return 3, 0 end  -- 扩展 A
    local r = freq[text]
    if r then return 1, r end                              -- 主词库有，按词频
    return 2, 0                                            -- 基本区但主词库没有
end

-- 判断当前是否在拆字：优先看 segment tag，取不到退回看输入码前缀
local function in_radical_lookup(env)
    local ctx = env.engine.context
    local ok, seg = pcall(function() return ctx.composition:back() end)
    if ok and seg then
        local ok2, has = pcall(function() return seg:has_tag('radical_lookup') end)
        if ok2 and has ~= nil then return has end
    end
    return ctx.input:match('^uu') ~= nil
end

local function filter(input, env)
    if not in_radical_lookup(env) then
        for cand in input:iter() do yield(cand) end
        return
    end

    -- 收集并打分。i 记录原始顺序，用于同分时保持稳定
    local list, i = {}, 0
    for cand in input:iter() do
        i = i + 1
        local tier, rank = rank_of(cand.text)
        table.insert(list, { cand = cand, tier = tier, rank = rank, idx = i })
    end

    table.sort(list, function(a, b)
        if a.tier ~= b.tier then return a.tier < b.tier end
        if a.rank ~= b.rank then return a.rank < b.rank end
        return a.idx < b.idx
    end)

    for _, item in ipairs(list) do yield(item.cand) end
end

return filter
